default['jboss']['jboss_package'] = "/tmp/jboss.zip"
default['jboss']['jboss_url'] = "http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip"
default['jboss']['jboss_home'] = "/opt"
default['jboss']['jboss_user'] = "jboss-as"
default['jboss']['sample_app'] = "/tmp/testweb.zip"
default['jboss']['sample_app_url'] = "http://www.cumulogic.com/download/Apps/testweb.zip"